name: CI

on: [push, pull_request]

jobs:
  
  build_updates_only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Clean up files
        run: |
           rm _ark/songs/updates/update_song_catcher.dta
           rm _ark/songs/missing_song_data.dta
           rm _ark/songs/missing_song_data_updates.dta
           rm  -rf _ark/songs/dta_sections
           rm  -rf _ark/songs/dta_collection
           mv _ark/songs/beencaughtstealing _ark/songs/updates/beencaughtstealing
           mv _ark/songs/getupstandup _ark/songs/updates/getupstandup
           mv _ark/songs/nooneknows _ark/songs/updates/nooneknows
           mv _ark/songs/radarlove _ark/songs/updates/radarlove
           mv _ark/songs/thepoweroflove _ark/songs/updates/thepoweroflove
           mv _ark/songs/updates _ark/songs/songs_updates
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-YARG-Updates
          path: _ark/songs

  build_xbox_standard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          name: RB3DX-Xbox-Base
          path: _build/xbox
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Nightly Build - ${{ steps.latestCommit.outputs.commitSHA }}
          tag: ${{ steps.latestCommit.outputs.commitShortSHA }}
          file: Release/*
          file_glob: true
          body: |
            testing

  build_xbox_forceguitar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
          sed -i -e "s/;#define PAD_IS_ACTUAL_GUITAR (1)/#define PAD_IS_ACTUAL_GUITAR (1)/" _ark/config/dx_macros.dta
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-Base-Force-Guitar-Controller
          path: _build/xbox

  build_xbox_original_mids:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Revert mid updates to their originals
        run: |
          find _ark/songs/updates/ -name "*.mid" -type f -delete
          find _ark/songs/updates/ -empty -type d -delete
      - name: Disable mid updates in dta
        run: |
          python dependencies/dev_scripts/disable_chart_updates.py
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-original-mids
          path: _build/xbox

  build_xbox_original_mids_forceguitar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Revert mid updates to their originals
        run: |
          find _ark/songs/updates/ -name "*.mid" -type f -delete
          find _ark/songs/updates/ -empty -type d -delete
      - name: Disable mid updates in dta
        run: |
          python dependencies/dev_scripts/disable_chart_updates.py
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
          sed -i -e "s/;#define PAD_IS_ACTUAL_GUITAR (1)/#define PAD_IS_ACTUAL_GUITAR (1)/" _ark/config/dx_macros.dta
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-original-mids-Force-Guitar-Controller
          path: _build/xbox

  build_xbox_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Add rb3_plus keys into the patch ark
        run: |
          python dependencies/dev_scripts/add_rb3_plus_keys.py
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-keys
          path: _build/xbox

  build_ps3_standard:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          pip install gitpython
          pip install mido
          pip install requests
      - name: fetch TrueAncestor PKG Repacker
        run: |
          python dependencies/dev_scripts/download_ta_pkg_repacker.py
      - name: Remove Xbox files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
      - name: Print build info
        run: |
          $GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)".ToUpper()
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/windows/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-BLUS30463_00-RB3DXNITE"
          $packageversion="1.05"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: RB3DX-PS3-Base
          path: '*.pkg'

  build_ps3_original_mids:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          pip install gitpython
          pip install mido
          pip install requests
      - name: fetch TrueAncestor PKG Repacker
        run: |
          python dependencies/dev_scripts/download_ta_pkg_repacker.py
      - name: Revert mid updates to their originals
        run: |
          Get-ChildItem _ark/ -recurse -include *.mid | Sort-Object -Property FullName -Descending | remove-item
          Get-ChildItem -Recurse -Directory | ? { -Not ($_.EnumerateFiles('*',1) | Select-Object -First 1) } | Remove-Item -Recurse
      - name: Disable mid updates in dta
        run: |
          python dependencies/dev_scripts/disable_chart_updates.py
      - name: Remove Xbox files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
      - name: Print build info
        run: |
          $GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)".ToUpper()
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/windows/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-BLUS30463_00-RB3DXOMID"
          $packageversion="1.05"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: RB3DX-PS3-original-mids
          path: '*.pkg'

  build_ps3_keys:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          pip install gitpython
          pip install mido
          pip install requests
      - name: fetch TrueAncestor PKG Repacker
        run: |
          python dependencies/dev_scripts/download_ta_pkg_repacker.py
      - name: Add rb3_plus keys into the patch ark
        run: |
          python dependencies/dev_scripts/add_rb3_plus_keys.py
      - name: Remove Xbox files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
      - name: Print build info
        run: |
          $GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)".ToUpper()
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/windows/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-BLUS30463_00-RB3DXKEYS"
          $packageversion="1.05"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3
      
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: RB3DX-PS3-keys
          path: '*.pkg'

  build_ps3_stock_inst_mapping:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          pip install mido
          pip install gitpython
          pip install requests
      - name: fetch TrueAncestor PKG Repacker
        run: |
          python dependencies/dev_scripts/download_ta_pkg_repacker.py
      - name: Remove Xbox files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
      - name: Restore stock instrument mapping
        run: |
          python dependencies/dev_scripts/enable_stock_pad.py
      - name: Print build info
        run: |
          $GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)".ToUpper()
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/windows/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-BLUS30463_00-RB3DXINST"
          $packageversion="1.05"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: RB3DX-PS3-stock-instrument-mapping
          path: '*.pkg'
